### ISSUE TITLE
PHP 7.3, "filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated"

### ISSUE THREAD

**Issue by KiddoKenshin** [PHPMailer/PHPMailer#1572]
# Problem description
PHP 7.3 (Release Candidate 3),
PHPMailer->send() causes "filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated"

# Code to reproduce
use PHP 7.3, PHPMailer->send();

# Debug output
filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated

# Reference
https://wiki.php.net/rfc/deprecations_php_7_3#filter_flag_scheme_required_and_filter_flag_host_required

**Comment by Synchro** [comment]
Already fixed in master

**Comment by silviodelgado** [comment]
This error is also shown to me when I send and email.

**Comment by Synchro** [comment]
Like the thread already says, this has been fixed. Update your PHPMailer.

**Comment by silviodelgado** [comment]
My version is the last stable (6.0.7) and the problem are still there.

**Comment by Synchro** [comment]
The `FILTER_FLAG_SCHEME_REQUIRED` constant is not used anywhere in the current release. Double-check your versions.

**Comment by silviodelgado** [comment]
Sorry for my complain. 
My VSCode cache from Github was keeping the old code, instead of update it (even after composer.json update)

**Comment by mjkatgithub** [comment]
> Sorry for my complain.
> My VSCode cache from Github was keeping the old code, instead of update it (even after composer.json update)

in my composer.json is
```
"phpmailer/phpmailer": "v6.1.7",
```
how did you force composer to use the new version?

**Comment by Synchro** [comment]
Change your composer.json to:

    "phpmailer/phpmailer": "^6.1",

Then update (just PHPMailer) using `composer update phpmailer/phpmailer`. This pattern will match semver numbering and will get the latest version of PHPMailer 6.x.x, currently 6.1.8.
