### ISSUE TITLE
iCalendar invite is not showing RSVP buttons in email clients

### ISSUE THREAD

**Issue by ghost** [PHPMailer/PHPMailer#175]
I'm using PHPMailer to send email. My ics content is:

```
BEGIN:VCALENDAR
METHOD:REQUEST
VERSION:2.0
PRODID:-//FooBar//FooBar Calendar//EN
BEGIN:VEVENT
UID:8f5a0777-bf6d-17d2-f14a-52e7feedf810
ORGANIZER;CN=Foo:foo@bar.com
DTSTART:20140130T191500Z
DTEND:20140130T194500Z
DTSTAMP:20140129T144300Z
SUMMARY:Foo Bar 11
DESCRIPTION:
END:VEVENT
END:VCALENDAR
```

For some reason I don't see the expected RSVP buttons in any email clients. Both Gmail and Mac Mail simply include the ics as a file attachment, I assume as a fallback. So there must be something wrong. I have not tried Outlook, but I don't see any reason why it would be different in a third client. The contents of an email being sent are below. Can you see anything that looks incorrect? Thank you.

```
Return-Path: REDACTED
Received: REDACTED
Date: Wed, 29 Jan 2014 09:43:18 -0500
Return-Path: REDACTED
To: REDACTED
From: REDACTED
Reply-To: REDACTED
Subject: Meeting - Foo Bar 11
Message-ID: <7004961cd9df04181047296f98260834@localhost>
X-Priority: 3
X-Mailer: PHPMailer 5.2.7 (https://github.com/PHPMailer/PHPMailer/)
MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary="b1_7004961cd9df04181047296f98260834"
Content-Transfer-Encoding: base64

--b1_7004961cd9df04181047296f98260834
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

VG86IEZvbyBCYXINCg0KDQpBZG1pbmlzdHJhdG9yIGhhcyBpbnZpdGVkIHlvdSB0byBhIE1lZXRpbmcNCg0KDQpTdWJqZWN0OiBGb28gQmFyIDExDQoNClN0YXJ0IERhdGU6IDAxLzMwLzIwMTQgMDI6MTVwbSBFU1QoLTA1OjAwKQ0KDQpFbmQgRGF0ZTogMDEvMzAvMjAxNCAwMjo0NXBtIEVTVCgtMDU6MDApDQoNCg0KRGVzY3JpcHRpb246IA0KDQoNCkFjY2VwdCB0aGlzIG1lZXRpbmc6DQoNCmh0dHA6Ly9sb2NhbGhvc3Q6ODg4OC9pbmRleC5waHA/ZW50cnlQb2ludD1hY2NlcHREZWNsaW5lJm1vZHVsZT1NZWV0aW5ncyZ1c2VyX2lkPTEmcmVjb3JkPThmNWEwNzc3LWJmNmQtMTdkMi1mMTRhLTUyZTdmZWVkZjgxMCZhY2NlcHRfc3RhdHVzPWFjY2VwdA0KDQoNClRlbnRhdGl2ZWx5IEFjY2VwdCB0aGlzIG1lZXRpbmcNCg0KaHR0cDovL2xvY2FsaG9zdDo4ODg4L2luZGV4LnBocD9lbnRyeVBvaW50PWFjY2VwdERlY2xpbmUmbW9kdWxlPU1lZXRpbmdzJnVzZXJfaWQ9MSZyZWNvcmQ9OGY1YTA3NzctYmY2ZC0xN2QyLWYxNGEtNTJlN2ZlZWRmODEwJmFjY2VwdF9zdGF0dXM9dGVudGF0aXZlDQoNCg0KRGVjbGluZSB0aGlzIG1lZXRpbmcNCg0KaHR0cDovL2xvY2FsaG9zdDo4ODg4L2luZGV4LnBocD9lbnRyeVBvaW50PWFjY2VwdERlY2xpbmUmbW9kdWxlPU1lZXRpbmdzJnVzZXJfaWQ9MSZyZWNvcmQ9OGY1YTA3NzctYmY2ZC0xN2QyLWYxNGEtNTJlN2ZlZWRmODEwJmFjY2VwdF9zdGF0dXM9ZGVjbGluZQ0KDQo=


--b1_7004961cd9df04181047296f98260834
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: base64

PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgVHJhbnNpdGlvbmFsLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSL3hodG1sMS9EVEQveGh0bWwxLXRyYW5zaXRpb25hbC5kdGQiPg0KPGh0bWwgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiIGxhbmc9J2VuX3VzJz4NCjxoZWFkPg0KPG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9VVRGLTgiIC8+DQo8dGl0bGU+DQpNZWV0aW5nIC0gRm9vIEJhciAxMQ0KPC90aXRsZT4NCjwvaGVhZD4NCjxib2R5Pg0KVG86IEFkbWluaXN0cmF0b3I8YnIgLz48YnIgLz4NCkFkbWluaXN0cmF0b3IgaGFzIGludml0ZWQgeW91IHRvIGEgTWVldGluZzxiciAvPjxiciAvPg0KU3ViamVjdDogRm9vIEJhciAxMTxiciAvPg0KU3RhcnQgRGF0ZTogMDEvMzAvMjAxNCAwMjoxNXBtIEVTVCgtMDU6MDApPGJyIC8+DQpFbmQgRGF0ZTogMDEvMzAvMjAxNCAwMjo0NXBtIEVTVCgtMDU6MDApPGJyIC8+DQoNCkRlc2NyaXB0aW9uOiA8YnIgLz48YnIgLz4NCkFjY2VwdCB0aGlzIG1lZXRpbmc6PGJyIC8+DQo8YSBocmVmPSJodHRwOi8vbG9jYWxob3N0Ojg4ODgvaW5kZXgucGhwP2VudHJ5UG9pbnQ9YWNjZXB0RGVjbGluZSZtb2R1bGU9TWVldGluZ3MmdXNlcl9pZD0xJnJlY29yZD04ZjVhMDc3Ny1iZjZkLTE3ZDItZjE0YS01MmU3ZmVlZGY4MTAmYWNjZXB0X3N0YXR1cz1hY2NlcHQiPmh0dHA6Ly9sb2NhbGhvc3Q6ODg4OC9pbmRleC5waHA/ZW50cnlQb2ludD1hY2NlcHREZWNsaW5lJm1vZHVsZT1NZWV0aW5ncyZ1c2VyX2lkPTEmcmVjb3JkPThmNWEwNzc3LWJmNmQtMTdkMi1mMTRhLTUyZTdmZWVkZjgxMCZhY2NlcHRfc3RhdHVzPWFjY2VwdDwvYT48YnIgLz48YnIgLz4NClRlbnRhdGl2ZWx5IEFjY2VwdCB0aGlzIG1lZXRpbmc8YnIgLz4NCjxhIGhyZWY9Imh0dHA6Ly9sb2NhbGhvc3Q6ODg4OC9pbmRleC5waHA/ZW50cnlQb2ludD1hY2NlcHREZWNsaW5lJm1vZHVsZT1NZWV0aW5ncyZ1c2VyX2lkPTEmcmVjb3JkPThmNWEwNzc3LWJmNmQtMTdkMi1mMTRhLTUyZTdmZWVkZjgxMCZhY2NlcHRfc3RhdHVzPXRlbnRhdGl2ZSI+aHR0cDovL2xvY2FsaG9zdDo4ODg4L2luZGV4LnBocD9lbnRyeVBvaW50PWFjY2VwdERlY2xpbmUmbW9kdWxlPU1lZXRpbmdzJnVzZXJfaWQ9MSZyZWNvcmQ9OGY1YTA3NzctYmY2ZC0xN2QyLWYxNGEtNTJlN2ZlZWRmODEwJmFjY2VwdF9zdGF0dXM9dGVudGF0aXZlPC9hPjxiciAvPjxiciAvPg0KRGVjbGluZSB0aGlzIG1lZXRpbmc8YnIgLz4NCjxhIGhyZWY9Imh0dHA6Ly9sb2NhbGhvc3Q6ODg4OC9pbmRleC5waHA/ZW50cnlQb2ludD1hY2NlcHREZWNsaW5lJm1vZHVsZT1NZWV0aW5ncyZ1c2VyX2lkPTEmcmVjb3JkPThmNWEwNzc3LWJmNmQtMTdkMi1mMTRhLTUyZTdmZWVkZjgxMCZhY2NlcHRfc3RhdHVzPWRlY2xpbmUiPmh0dHA6Ly9sb2NhbGhvc3Q6ODg4OC9pbmRleC5waHA/ZW50cnlQb2ludD1hY2NlcHREZWNsaW5lJm1vZHVsZT1NZWV0aW5ncyZ1c2VyX2lkPTEmcmVjb3JkPThmNWEwNzc3LWJmNmQtMTdkMi1mMTRhLTUyZTdmZWVkZjgxMCZhY2NlcHRfc3RhdHVzPWRlY2xpbmU8L2E+PGJyIC8+PGJyIC8+DQo8L2JvZHk+DQo8L2h0bWw+


--b1_7004961cd9df04181047296f98260834
Content-Type: text/calendar; method=REQUEST; charset=UTF-8
Content-Transfer-Encoding: base64

QkVHSU46VkNBTEVOREFSDQpNRVRIT0Q6UkVRVUVTVA0KVkVSU0lPTjoyLjANClBST0RJRDotLy9Gb29CYXIvL0Zvb0JhciBDYWxlbmRhci8vRU4NCkJFR0lOOlZFVkVOVA0KVUlEOjhmNWEwNzc3LWJmNmQtMTdkMi1mMTRhLTUyZTdmZWVkZjgxMA0KT1JHQU5JWkVSO0NOPUZvbzpmb29AYmFyLmNvbQ0KRFRTVEFSVDoyMDE0MDEzMFQxOTE1MDBaDQpEVEVORDoyMDE0MDEzMFQxOTQ1MDBaDQpEVFNUQU1QOjIwMTQwMTI5VDE0NDMwMFoNClNVTU1BUlk6Rm9vIEJhciAxMQ0KREVTQ1JJUFRJT046DQpFTkQ6VkVWRU5UDQpFTkQ6VkNBTEVOREFSDQo=



--b1_7004961cd9df04181047296f98260834--
```

P.S. Sorry about it being base64 encoded. I wanted to show a true representation of the email instead of changing it any way that may skew the results. I just use http://www.base64decode.org/ to decode the contents.

P.P.S. The base64 contents show as one string, but the email is sent with a max of 1000 characters per line. I just needed to remove some sensitive information, so I had to re-encode those parts, which removed the breaks.

**Comment by CM8Solutions** [comment]
Hi!

Hopefully someone is still following this topic because I really need help with this RSVP button issue. The thing is that I don't want those buttons to to appear so that the event is automatically accepted (mainly in Outlook). Any ideas how to do that?

**Comment by Synchro** [comment]
If you don't want to give them a choice, why even ask? Just add them to the event without asking.

**Comment by CM8Solutions** [comment]
But how do I do that? What changes do I have to make?

Thanks a lot!

**Comment by Synchro** [comment]
I've no idea - you'd need to talk to the calendar server directly, not via email.

**Comment by Luisinho77** [comment]
Hey friend, 

I've just read amazing news, you;ve got  to see it with your own eyes! Just take a look <http://member.jbeamgolf.com/e4pcdfx>


Take care, ljlorente

**Comment by kamil-kielczewski** [comment]
For me problem was that RSVP buttons not appear in Gmail although I send valid .ics file. The solution was add proper mime type to email .ics file attachement: 

Content-Type: text/calendar; method=REQUEST; charset=UTF-8

I do it in laravel 5 in this way:
```
    Mail::queue('emails.reservationInvitation', compact('guest','attendeesList','reservation', 'dayBegin', 'dayName', 'hourBegin', 'hourEnd', 'length' )
            , function ($message) use ($reservation, $subject, $guest, $icalendar) {
                $message->attachData($icalendar, "invite.ics", ['mime' => 'text/calendar; method=REQUEST; charset=UTF-8']);
                $message->to($guest['email'])->subject($subject); // email = $reservation->user->name
            });
```

where $icalendar was string with content of my .ics file.

**Comment by Synchro** [comment]
You can specify a MIME type when you add an attachment:

    $mail->addAttachment('path/to/calendar.ics', 'calendar.ics', 'base64', 'text/calendar');

If you don't provide a MIME type manually like this, PHPMailer has a built-in list of MIME types that it associates with file extensions automatically, however `ics` was missing from the list. I've now added it in the 6.0 branch.

Note that when you use PHPMailer's built-in embedded iCal support (via the `Ical` property mentioned in this thread), it did already set the MIME type correctly.

**Comment by christophercarlsson** [comment]
If I add an Ical and attach a file at the same time, the Ical info is not sent with the mail. If I remove the attachment, the mail is sent with the Ical info (however not recognized by Outlook/Mail..).

My PHP
`$fp = fopen($_SERVER['DOCUMENT_ROOT'] . "/ical.ics", "wb");
		fwrite($fp, $this->renderIcs($events, false));
		fclose($fp);

		$mail = new PHPMailer();
		$mail->CharSet = "UTF-8";
		$mail->isSMTP();
		$mail->IsHTML(false);
		$mail->Host = env('MAIL_HOST');
		$mail->Port = env('MAIL_PORT');
		$mail->SMTPAuth = true;
		$mail->Username = env('MAIL_USERNAME');
		$mail->Password = env('MAIL_PASSWORD');
		$mail->setFrom($email, $name);
		$mail->addAddress($email, $name);
		$mail->Subject = trans('emails.reservation.email_subject', ['reservation_title' => strip_tags($reservation->title)]);
		$mail->Body = "test";
		$mail->AltBody = "test";
		$mail->addAttachment($_SERVER['DOCUMENT_ROOT'] . "/ical.ics", 'calendar.ics', 'base64', 'text/calendar');
		$mail->Ical = $this->renderIcs($events, false);

		$mail->Send();
		}`

Gives me the following mail:
> Date: Tue, 1 Aug 2017 14:44:29 +0000
> To: xxx
> From: xxx
> Subject: Calendar Invite: asd
> Message-ID: <7401f051c441e65793fba6425f30fccd@laravel>
> X-Mailer: PHPMailer 5.2.24 (https://github.com/PHPMailer/PHPMailer)
> MIME-Version: 1.0
> Content-Type: multipart/mixed;
> 	boundary="b1_7401f051c441e65793fba6425f30fccd"
> Content-Transfer-Encoding: 8bit
> 
> This is a multi-part message in MIME format.
> 
> --b1_7401f051c441e65793fba6425f30fccd
> Content-Type: multipart/alternative;
> 	boundary="b2_7401f051c441e65793fba6425f30fccd"
> 
> --b2_7401f051c441e65793fba6425f30fccd
> Content-Type: text/plain; charset=us-ascii
> 
> test
> 
> 
> --b2_7401f051c441e65793fba6425f30fccd
> Content-Type: text/html; charset=us-ascii
> 
> test
> 
> 
> 
> --b2_7401f051c441e65793fba6425f30fccd--
> 
> --b1_7401f051c441e65793fba6425f30fccd
> Content-Type: text/calendar; name="calendar.ics"
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment; filename=calendar.ics
> 
> VkVSU0lPTjoyLjANCkJFR0lOOlZDQUxFTkRBUg0KUFJPRElEOi0vL2hhY2tzdy9oYW5kY2FsLy9OT05TR01MIHYxLjAvL0VODQpNRVRIT0Q6UkVRVUVTVA0KQkVHSU46VkVWRU5UDQpVSUQ6eHh4LTEyMy14eHgNCk9SR0FOSVpFUjtDTj14eHg6bWFpbHRvOnh4eA0KRFRTVEFSVDoyMDE3MDgwMVQxMzMwMDBaDQpEVEVORDoyMDE3MDgwMVQxMzQ1MDBaDQpEVFNUQU1QOjIwMTcwODAxVDE0NDQyOVoNClNVTU1BUlk6YXNkDQpERVNDUklQVElPTjp0ZXN0DQpMT0NBVElPTjpUZXN0aW5nIHJlc291cmNlDQpTRVFVRU5DRToxDQpFTkQ6VkVWRU5UDQpFTkQ6VkNBTEVOREFS
> 
> 
> --b1_7401f051c441e65793fba6425f30fccd--

However - removing the attached file generates this:

> Date: Tue, 1 Aug 2017 14:44:17 +0000
> To: xxx
> From: xxx
> Subject: Calendar Invite: asd
> Message-ID: <0665272647344ea75df23a6698e8a8ff@laravel>
> X-Mailer: PHPMailer 5.2.24 (https://github.com/PHPMailer/PHPMailer)
> MIME-Version: 1.0
> Content-Type: multipart/alternative;
> 	boundary="b1_0665272647344ea75df23a6698e8a8ff"
> Content-Transfer-Encoding: 8bit
> 
> This is a multi-part message in MIME format.
> 
> --b1_0665272647344ea75df23a6698e8a8ff
> Content-Type: text/plain; charset=us-ascii
> 
> test
> 
> 
> --b1_0665272647344ea75df23a6698e8a8ff
> Content-Type: text/html; charset=us-ascii
> 
> test
> 
> 
> --b1_0665272647344ea75df23a6698e8a8ff
> Content-Type: text/calendar; method=REQUEST; charset=UTF-8
> Content-Transfer-Encoding: 8bit
> 
> VERSION:2.0
> BEGIN:VCALENDAR
> PRODID:-//hacksw/handcal//NONSGML v1.0//EN
> METHOD:REQUEST
> BEGIN:VEVENT
> UID:xxx-123-xxx
> ORGANIZER;CN=xxx:mailto:xxx
> DTSTART:20170801T131500Z
> DTEND:20170801T133000Z
> DTSTAMP:20170801T144417Z
> SUMMARY:asd
> DESCRIPTION:test
> LOCATION:Testing resource
> SEQUENCE:1
> END:VEVENT
> END:VCALENDAR
> 
> 
> 
> --b1_0665272647344ea75df23a6698e8a8ff--
> 

What is causing this and why is it not working? Seemingly my ics file is valid and according to what i see in this thread..

**Comment by Synchro** [comment]
Thanks for the clear description. This is down to PHPMailer's preset MIME structures - as soon as you add attachments, the message is built using the `alt_attach` structure, which doesn't have Ical support. I've just pushed a change to the 6.0 branch that does support for that, so you can at least attempt this workaround - please report your results!

**Comment by christophercarlsson** [comment]
Thank you, that worked. They both are included now. However - I still get no RSVP buttons in either of Mac Mail and Outlook. Any idea on what is wrong? Im able to click the attached file in Mail and get it to add it to my calendar, but the same can not be done i Outlook.

> Date: Tue, 1 Aug 2017 15:42:22 +0000
> To: xxx
> From: xxx
> Subject: Calendar Invite: test
> Message-ID: <7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e@laravel>
> X-Mailer: PHPMailer 6.0.0 (https://github.com/PHPMailer/PHPMailer)
> MIME-Version: 1.0
> Content-Type: multipart/mixed;
> 	boundary="b1_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e"
> Content-Transfer-Encoding: 8bit
> 
> This is a multi-part message in MIME format.
> --b1_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e
> Content-Type: multipart/alternative;
> 	boundary="b2_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e"
> 
> --b2_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e
> Content-Type: text/plain; charset=us-ascii
> 
> test
> 
> --b2_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e
> Content-Type: text/html; charset=us-ascii
> 
> test
> 
> --b2_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e
> Content-Type: text/calendar; method=REQUEST; charset=UTF-8
> Content-Transfer-Encoding: 8bit
> 
> BEGIN:VCALENDAR
> VERSION:2.0
> PRODID:-//Microsoft Corporation//Outlook 11.0 MIMEDIR//EN
> METHOD:REQUEST
> BEGIN:VEVENT
> UID:book-8@getmeetio.com
> ORGANIZER;CN=Christopher Carlsson:mailto:xxxx
> ATTENDEE;ROLE=REQ-PARTICIPANT;CN=Christopher Carlsson:mailto:xxxx
> ACTION;RSVP=TRUE;CN=Christopher Carlsson;X-NUM-GUESTS=0:mailto:xxx
> DTSTART:20170802T090000Z
> DTEND:20170802T091500Z
> DTSTAMP:20170801T154222Z
> SUMMARY:test
> DESCRIPTION:test
> LOCATION:Testing resource
> SEQUENCE:1
> STATUS:CONFIRMED
> END:VEVENT
> END:VCALENDAR
> 
> --b2_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e--
> 
> --b1_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e
> Content-Type: text/calendar; name="calendar.ics"
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment; filename=calendar.ics
> 
> QkVHSU46VkNBTEVOREFSDQpWRVJTSU9OOjIuMA0KUFJPRElEOi0vL01pY3Jvc29mdCBDb3Jwb3JhdGlvbi8vT3V0bG9vayAxMS4wIE1JTUVESVIvL0VODQpNRVRIT0Q6UkVRVUVTVA0KQkVHSU46VkVWRU5UDQpVSUQ6Ym9vay04QGdldG1lZXRpby5jb20NCk9SR0FOSVpFUjtDTj1DaHJpc3RvcGhlciBDYXJsc3NvbjptYWlsdG86eHh4DQpBVFRFTkRFRTtST0xFPVJFUS1QQVJUSUNJUEFOVDtDTj1DaHJpc3RvcGhlciBDYXJsc3NvbjptYWlsdG86eHh4DQpBQ1RJT047UlNWUD1UUlVFO0NOPUNocmlzdG9waGVyIENhcmxzc29uO1gtTlVNLUdVRVNUUz0wOm1haWx0bzp4eHgNCkRUU1RBUlQ6MjAxNzA4MDJUMDkwMDAwWg0KRFRFTkQ6MjAxNzA4MDJUMDkxNTAwWg0KRFRTVEFNUDoyMDE3MDgwMVQxNTQyMjJaDQpTVU1NQVJZOnRlc3QNCkRFU0NSSVBUSU9OOnRlc3QNCkxPQ0FUSU9OOlRlc3RpbmcgcmVzb3VyY2UNClNFUVVFTkNFOjENClNUQVRVUzpDT05GSVJNRUQNCkVORDpWRVZFTlQNCkVORDpWQ0FMRU5EQVI=
> 
> --b1_7f2ef0f72584f4006430793cafbac142d487260b5eeac5ab78c0058e50a9076e--

**Comment by Synchro** [comment]
If you do just one or the other, do the buttons your'e expecting appear in either? Do you have an example message that does work correctly that we could compare it with?

**Comment by christophercarlsson** [comment]
Im comparing to the reply above that @adsega posted, saying he could get it to work in Outlook. Buttons don't appear with just one or the other.

**Comment by Synchro** [comment]
I've pushed some experimental changes in [6.0-ical](https://github.com/PHPMailer/PHPMailer/tree/6.0-ical) - the main difference is the addition of a `Content-Class` header as suggested by articles [here](https://blogs.msdn.microsoft.com/webdav_101/2008/02/26/building-vcalendar-content-without-an-microsoft-api-is-not-supported-by-ms/) and [here](http://mavetju.org/programming/outlook-ics.php). Please can you give that a try?

**Comment by christophercarlsson** [comment]
Thank you for your continued efforts. Unfortunately it still does not work. The mail source is the following, but still no RSVP/ability to add to calendar in outlook nor Mail.

> Subject: Calendar Invite: Test
> Message-ID: <d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87@laravel>
> X-Mailer: PHPMailer 6.0.0 (https://github.com/PHPMailer/PHPMailer)
> MIME-Version: 1.0
> Content-Class: urn:content-classes:calendarmessage
> Content-Type: multipart/mixed;
> 	boundary="b1_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87"
> Content-Transfer-Encoding: 8bit
> 
> This is a multi-part message in MIME format.
> --b1_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87
> Content-Type: multipart/alternative;
> 	boundary="b2_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87"
> 
> --b2_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87
> Content-Type: text/plain; charset=us-ascii
> 
> test
> 
> --b2_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87
> Content-Type: text/html; charset=us-ascii
> 
> test
> 
> --b2_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87
> Content-Type: text/calendar; method=REQUEST; charset=UTF-8
> Content-Transfer-Encoding: 8bit
> Content-Class: urn:content-classes:calendarmessage
> 
> BEGIN:VCALENDAR
> METHOD:REQUEST
> PRODID:Microsoft Exchange Server 2010
> VERSION:2.0
> BEGIN:VEVENT
> UID:book-25@xxx
> ORGANIZER;CN=Christopher Carlsson:mailto:xxx
> ATTENDEE;ROLE=REQ-PARTICIPANT;CN=Christopher Carlsson:mailto:xxx
> ACTION;RSVP=TRUE;CN=Christopher Carlsson;X-NUM-GUESTS=0:mailto:xxx
> DTSTART:20170804T134500Z
> DTEND:20170804T140000Z
> DTSTAMP:20170804T112625Z
> SUMMARY:Test
> DESCRIPTION:test
> LOCATION:Testresurs
> SEQUENCE:1
> STATUS:CONFIRMED
> END:VEVENT
> END:VCALENDAR
> 
> --b2_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87--
> 
> --b1_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87
> Content-Type: text/calendar; name="calendar.ics"
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment; filename=calendar.ics
> 
> QkVHSU46VkNBTEVOREFSDQpNRVRIT0Q6UkVRVUVTVA0KUFJPRElEOk1pY3Jvc29mdCBFeGNoYW5nZSBTZXJ2ZXIgMjAxMA0KVkVSU0lPTjoyLjANCkJFR0lOOlZFVkVOVA0KVUlEOmJvb2stMjVAeHh4DQpPUkdBTklaRVI7Q049Q2hyaXN0b3BoZXIgQ2FybHNzb246bWFpbHRvOnh4eA0KQVRURU5ERUU7Uk9MRT1SRVEtUEFSVElDSVBBTlQ7Q049Q2hyaXN0b3BoZXIgQ2FybHNzb246bWFpbHRvOnh4eA0KQUNUSU9OO1JTVlA9VFJVRTtDTj1DaHJpc3RvcGhlciBDYXJsc3NvbjtYLU5VTS1HVUVTVFM9MDptYWlsdG86eHh4DQpEVFNUQVJUOjIwMTcwODA0VDEzNDUwMFoNCkRURU5EOjIwMTcwODA0VDE0MDAwMFoNCkRUU1RBTVA6MjAxNzA4MDRUMTEyNjI1Wg0KU1VNTUFSWTpUZXN0DQpERVNDUklQVElPTjp0ZXN0DQpMT0NBVElPTjpUZXN0cmVzdXJzDQpTRVFVRU5DRToxDQpTVEFUVVM6Q09ORklSTUVEDQpFTkQ6VkVWRU5UDQpFTkQ6VkNBTEVOREFS
> 
> --b1_d83d69dae575b544ae866adb06fa17e53e7014bfcc12978a468b83895932fa87--
>

**Comment by Synchro** [comment]
Does anyone have known-working examples for all the places that we want this to work that they could share? I'm working pretty much blind here.

**Comment by Synchro** [comment]
I happened to get sent an invitation from Apple's iCal service on iCloud. The email structure looks like this:

```
Content-Type: multipart/mixed; 
	boundary="----=_Part_889321_1826442293.1503391415807"

------=_Part_889321_1826442293.1503391415807
Content-Type: multipart/alternative; 
	boundary="----=_Part_889322_1826442187.1503391415807"

------=_Part_889322_1826442187.1503391415807
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-Disposition: inline

text part

------=_Part_889322_1826442187.1503391415807
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-Disposition: inline


HTML part

------=_Part_889322_1826442187.1503391415807--

------=_Part_889321_1826442293.1503391415807
Content-Type: text/calendar; method=REQUEST
Content-Transfer-Encoding: Base64
Content-Disposition: attachment; filename=iCal-20170822-014335.ics

ical part

------=_Part_889321_1826442293.1503391415807--
```

This message does nothing special in Mail on either macOS or iOS. There are buttons displayed, but they are just HTML from the HTML part, and the iCal part is shown as an attachment. Note that the `text/calendar` part is not part of the `multipart/alternative` structure - it's a simple attachment within the root `multipart/mixed` element. That said, while it did nothing within Mail, the Calendar app on macOS displayed a notification several minutes later containing close and accept buttons, though I have no way of telling if this was triggered by the email or one of my calendar subscriptions. What I really need is details of the MIME structure & headers that causes Outlook to do its thing.

**Comment by gunkire** [comment]
https://forums.phpfreaks.com/topic/157171-solved-phpmailer-custom-content/?p=829136

**Comment by Synchro** [comment]
@gunkire The PHPMailer code is already doing the same as what's in that example.

**Comment by christophercarlsson** [comment]
I've finally solved this outside of PHPMailer, using PHP's own mail function. The issue seems to have been that the VCALENDAR object needed to have a timezone specified - this gave me the RSVP buttons.

`$reservation = Reservation::with('user')->with('resource')->find($id);
		$boundary = "--" . md5(time());
		$origin_format = 'Y-m-d H:i:s';
		$format = 'Ymd\THis';

		$headers = "From: My sender <my@sender.com>\n";
		$headers .= "Reply-To: My sender <my@sender.com>\n";
		$headers .= "Content-Type: text/calendar; method=REQUEST;boundary=\"" . $boundary . "\";charset=\"utf-8\"\n";
		$headers .= "Content-Transfer-Encoding: 7bit\n";

		$ical ="X-Mailer: Microsoft Office Outlook 12.0
BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 12.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:UTC
BEGIN:STANDARD
DTSTART:20171010T000000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20170310T000000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN=\"'" . $reservation->user->name . "'\";RSVP=TRUE:mailto:" . $reservation->user->email . "
CLASS:PUBLIC
CREATED:" . Carbon::now()->format('Ymd\THis') . "
DTEND;TZID=\"UTC\":" . Carbon::createFromFormat($origin_format, $reservation->ends_at)->format($format) . "
DTSTAMP:" . Carbon::now()->format('Ymd\THis') . "
DTSTART;TZID=\"UTC\":" . Carbon::createFromFormat($origin_format, $reservation->starts_at)->format($format) . "
LAST-MODIFIED:20171113T133000
LOCATION:" . $reservation->resource->label . "
ORGANIZER;CN=Meetio Book:mailto:my@sender.com
PRIORITY:5
SEQUENCE:1
SUMMARY:Updated: " . $reservation->title . "
TRANSP:OPAQUE
UID:" . str_random(40) . "
END:VEVENT
END:VCALENDAR";
		$subject = $reservation->title;

		$mail_sent = mail($reservation->user->email, $subject, $ical, $headers);`

Hope this helps you solve the issue in PHPMailer.

**Comment by omocinteractive** [comment]
... is there any solution with PhpMailer 5? Maybe in the new version of PhpMailer?

**Comment by babuhacker** [comment]
i have a doubt.
$mail->Username   = "xxxxx@gmail.com";  // GMAIL username
$mail->Password   = "********";            // GMAIL password

it will steal my gmail username and password.
why we give gmail password.
what should i do.

**Comment by eltharin** [comment]
You can try to set those headers for PHPMAILER : 
$mail->CharSet = 'utf-8';
$mail->ContentType = 'text/calendar;method=REQUEST';
$mail->Encoding = '7bit';

**Comment by Synchro** [comment]
Look at the code; if you use PHPMailer’s iCal support, it adds exactly that header already.

**Comment by jdudley1123** [comment]
I think I've cracked it. Tested on Gmail and on Outlook. Both result in properly formatted calendar invites with RSVP buttons.

I don't know exactly why it works and other solutions don't, I just know that it does! I kept trying things from StackOverflow answers and suggestions in this thread and elsewhere until I got something that worked.

The VCALENDAR object looks like this:
````
BEGIN:VCALENDAR
PRODID:-//Mailer//NONSGML v1.0//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTART:20200523T080000Z
DTEND:20200523T090000Z
DTSTAMP:20200522T133929Z
ORGANIZER;CN="Joseph":mailto:joseph@example.com
UID:e8e8a1f77808cd0719daf26f973e556e@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="Heidi";X-NUM-GUESTS=0:mailto:heidi@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="James";X-NUM-GUESTS=0:mailto:james@example.com
CREATED:20200522T133929Z
DESCRIPTION:This is a test invitation
LAST-MODIFIED:20200522T133929Z
SUMMARY:Test event
LOCATION:London
END:VEVENT
END:VCALENDAR
````

The code that produced it looks like this:

````
// Content
$location           = "London";
$date               = '20200523';
$startTime          = '0800';
$endTime            = '0900';
$subject            = 'Test event';
$desc               = 'This is a test invitation';

$organizer          = 'Joseph';

$organizer_email    = 'joseph@example.com';   
$participant_name_1 = 'Heidi';
$participant_email_1= 'heidi@example.com';
$participant_name_2 = 'James';
$participant_email_2= 'james@example.com';

//Be very careful with this string. You may need to add CLRF (\r\n) line breaks depending on how your server handles line endings.
$ical_content = 'BEGIN:VCALENDAR
PRODID:-//Mailer//NONSGML v1.0//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTART:'.$date.'T'.$startTime.'00Z
DTEND:'.$date.'T'.$endTime.'00Z
DTSTAMP:' . gmdate('Ymd').'T'. gmdate('His') . 'Z
ORGANIZER;CN="'.$organizer.'":mailto:'.$organizer_email.'
UID:' . md5(uniqid(mt_rand(), true)) . '@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="'.$participant_name_1.'";X-NUM-GUESTS=0:mailto:'.$participant_email_1.'
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="'.$participant_name_2.'";X-NUM-GUESTS=0:mailto:'.$participant_email_2.'
CREATED:' . gmdate('Ymd').'T'. gmdate('His') . 'Z
DESCRIPTION:'.$desc.'
LAST-MODIFIED:' . gmdate('Ymd').'T'. gmdate('His') . 'Z
SUMMARY:'.$subject.'
LOCATION:'.$location.'
END:VEVENT
END:VCALENDAR';

$mail->ContentType = 'text/calendar'; //This seems to be important for Outlook
$mail->Subject = 'Testing testing 123';
$mail->Body = 'Testing testing 321'; 
$mail->AltBody = $ical_content;
$mail->Ical = $ical_content;
$mail->addStringAttachment($ical_content, 'ical.ics', 'base64', 'application/ics; name="ical.ics"'); //This seems to be important for Gmail

//From
$mail->setFrom('joseph@example.com', 'Joseph');
$mail->addReplyTo('joseph@example.com', 'Joseph');

//Recipients
$mail->addAddress($participant_email_1, $participant_name_1);
$mail->addAddress($participant_email_2, $participant_name_2);

//Send
$mail->send();
````

**Comment by omocinteractive** [comment]
... this is what it looks like for me in Outlook 365 (for a single event):
![screenshot 118](https://user-images.githubusercontent.com/20245225/83648326-329cf700-a5b6-11ea-9f55-f3b007fa6e6b.jpg)

**Comment by vikas-wadhwa** [comment]
I'm actually concerned in regards to @omocinteractive answer, because I cannot seem to get Outlook to recognize the DESCRIPTION field, and it looks like the image @omocinteractive posted also isn't showing the description (Which I assume should show up right below the location line)

Anyone else having issues with Outlook calendar not showing the DESCRIPTION value?

**Comment by Synchro** [comment]
We know that Outlook is a horrible buggy mess, but you'll get better responses about it from MS support forums rather than here.

**Comment by rohantapiyawala** [comment]
> I think I've cracked it. Tested on Gmail and on Outlook. Both result in properly formatted calendar invites with RSVP buttons.
> 
> I don't know exactly why it works and other solutions don't, I just know that it does! I kept trying things from StackOverflow answers and suggestions in this thread and elsewhere until I got something that worked.
> 
> The VCALENDAR object looks like this:
> 
> ```
> BEGIN:VCALENDAR
> PRODID:-//Mailer//NONSGML v1.0//EN
> VERSION:2.0
> CALSCALE:GREGORIAN
> METHOD:REQUEST
> BEGIN:VEVENT
> DTSTART:20200523T080000Z
> DTEND:20200523T090000Z
> DTSTAMP:20200522T133929Z
> ORGANIZER;CN="Joseph":mailto:joseph@example.com
> UID:e8e8a1f77808cd0719daf26f973e556e@example.com
> ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="Heidi";X-NUM-GUESTS=0:mailto:heidi@example.com
> ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="James";X-NUM-GUESTS=0:mailto:james@example.com
> CREATED:20200522T133929Z
> DESCRIPTION:This is a test invitation
> LAST-MODIFIED:20200522T133929Z
> SUMMARY:Test event
> LOCATION:London
> END:VEVENT
> END:VCALENDAR
> ```
> 
> The code that produced it looks like this:
> 
> ```
> // Content
> $location           = "London";
> $date               = '20200523';
> $startTime          = '0800';
> $endTime            = '0900';
> $subject            = 'Test event';
> $desc               = 'This is a test invitation';
> 
> $organizer          = 'Joseph';
> 
> $organizer_email    = 'joseph@example.com';   
> $participant_name_1 = 'Heidi';
> $participant_email_1= 'heidi@example.com';
> $participant_name_2 = 'James';
> $participant_email_2= 'james@example.com';
> 
> //Be very careful with this string. You may need to add CLRF (\r\n) line breaks depending on how your server handles line endings.
> $ical_content = 'BEGIN:VCALENDAR
> PRODID:-//Mailer//NONSGML v1.0//EN
> VERSION:2.0
> CALSCALE:GREGORIAN
> METHOD:REQUEST
> BEGIN:VEVENT
> DTSTART:'.$date.'T'.$startTime.'00Z
> DTEND:'.$date.'T'.$endTime.'00Z
> DTSTAMP:' . gmdate('Ymd').'T'. gmdate('His') . 'Z
> ORGANIZER;CN="'.$organizer.'":mailto:'.$organizer_email.'
> UID:' . md5(uniqid(mt_rand(), true)) . '@example.com
> ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="'.$participant_name_1.'";X-NUM-GUESTS=0:mailto:'.$participant_email_1.'
> ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="'.$participant_name_2.'";X-NUM-GUESTS=0:mailto:'.$participant_email_2.'
> CREATED:' . gmdate('Ymd').'T'. gmdate('His') . 'Z
> DESCRIPTION:'.$desc.'
> LAST-MODIFIED:' . gmdate('Ymd').'T'. gmdate('His') . 'Z
> SUMMARY:'.$subject.'
> LOCATION:'.$location.'
> END:VEVENT
> END:VCALENDAR';
> 
> $mail->ContentType = 'text/calendar'; //This seems to be important for Outlook
> $mail->Subject = 'Testing testing 123';
> $mail->Body = 'Testing testing 321'; 
> $mail->AltBody = $ical_content;
> $mail->Ical = $ical_content;
> $mail->addStringAttachment($ical_content, 'ical.ics', 'base64', 'application/ics; name="ical.ics"'); //This seems to be important for Gmail
> 
> //From
> $mail->setFrom('joseph@example.com', 'Joseph');
> $mail->addReplyTo('joseph@example.com', 'Joseph');
> 
> //Recipients
> $mail->addAddress($participant_email_1, $participant_name_1);
> $mail->addAddress($participant_email_2, $participant_name_2);
> 
> //Send
> $mail->send();
> ```

@jdudley1123 can you share how did u make RSVP button show up on gmail ? I tried the code u share and it doesnt execute. Im using classic php with files imported into the code. Will try with composer as well. Thanks in advance

**Comment by rohantapiyawala** [comment]
> @rohantapiyawala The code above won't execute, you'll need to do all the normal PHPMailer things first (see the tutorial). Once you've got a functional `$mail` object setting the content type, body etc. as I've described should work.

@jdudley1123 : Thanks for ur input and the code previously shared. I was able to solve the issue with both Google Cal and Outlook. Now my code produces RSVP button for both of them. Part I was missing was "Ical" parameter. Now I can even edit and delete my events using the ics file and PHPMailer. Cheers!

**Comment by sneha-surve** [comment]
@rohantapiyawala @jdudley1123  Can you please share what you did to have RSVP buttons on outlook?

**Comment by rohantapiyawala** [comment]
> @rohantapiyawala @jdudley1123 Can you please share what you did to have RSVP buttons on outlook?

If you can mail me your code I can help. Sharing a working code that I use to schedule meetings for my various committees:

`BEGIN:VCALENDAR
VERSION:2.0
PRODID://ABCD Events//iCal 2.1//EN
METHOD:REQUEST
X-WR-CALNAME:ABCD Event Calendar
X-WR-TIMEZONE:America/New_York
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:America/New_York
TZURL:http://tzurl.org/zoneinfo-outlook/America/New_York
X-LIC-LOCATION:America/New_York
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:EDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
TRANSP:OPAQUE
CREATED:20230423T045348Z
UID:WGFG20230423045348
SUMMARY:WGFG catch up ABCD Event
DTSTART;TZID=America/New_York:20230426T170000
DTEND;TZID=America/New_York:20230426T180000
LOCATION;ENCODING=QUOTED-PRINTABLE:
DTSTAMP:20230423T045348Z
ORGANIZER;CN=ABCD Events:mailto:calendarbot@abcd.org
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=<email>;X-NUM-GUESTS=0:mailto:<email>
STATUS:CONFIRMED
DESCRIPTION:A. Want to join the meeting from your computer, tablet or smartphone?
SEQUENCE:0
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT10M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR`

**Comment by sneha-surve** [comment]
`	$ical_content = "BEGIN:VCALENDAR
VERSION:2.0
PRODID://Drupal iCal API//EN
BEGIN:VEVENT
UID:http://www.icalmaker.com/event/d8fefcc9-a576-4432-8b20-40e90889affd
DTSTAMP:20230524T045941Z
DTSTART:20230525T060000Z
DTEND:20230525T100000Z
SUMMARY:Party in Daawat
LOCATION:Hotel Daawat, Ground Floor, Phase 5, Sector 59, Near Post Office, Mohali 160059.
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Ayush Mehr
 otra:mailto:xxxxxx@gmail.com
DESCRIPTION:Dinner
END:VEVENT
END:VCALENDAR";

    $mail = new PHPMailer(true);

    // Recipients.
    $mail->setfrom('xxxxx@gmail.com');
    $mail->addAddress('xxx@gmail.com');
    $mail->addreplyto('xx@xxx.com');
    // Content.
    // Set email format to HTML.
    $mail->isHTML(TRUE);
    $mail->isSMTP();
    // Set the SMTP server to send through.
    $mail->Host = 'smtp-mail.outlook.com';
    // Enable SMTP authentication.
    $mail->SMTPAuth = TRUE;
    // SMTP username.
    $mail->Username = 'xxxxx@gmail.com';
    // SMTP password.
    $mail->Password = 'xxxxxx;
    // Enable implicit TLS encryption.
    $mail->SMTPSecure = 'tls';
    $mail->Port       = '587';
	// $mail->CharSet = 'UTF-8';

    // This seems to be important for Outlook.
    // $mail->ContentType = 'text/calendar';
    $mail->Subject     = 'Here is the subject';
    $message           = 'This is the HTML message body <b>in bold!</b>';
    $mail->msgHTML($message);
	$mail->AltBody = $ical_content;
    $mail->Ical = $ical_content;
    // For sending ical.
    if (!empty($ical_content)) {
      $mail->addStringAttachment($ical_content, 'ical.ics', 'base64', 'text/calendar');
    }

    $mail->send();`
    
    My sample code is as mentioned above. I need to add the calendar event in Outlook, but currently its coming as ICS file attachment. What can be done here. Pls help. Thanks

**Comment by Odido** [comment]
see https://stackoverflow.com/questions/78352419/using-phpmailer-to-send-ical-but-outlook-thunderbird-do-not-recognize-the-ical/78354815#78354815 for the solution

**Comment by daveherman71** [comment]
The solution is actually a lot simpler than that.

Create the ical file using something like `https://kigkonsult.se/iCalcreator/` as recommended in the documentation. Then attach the file as follows:
```
$path= 'C:\PHPTemp\invitation.ics';
$name = basename($path);
$encoding = PHPMailer::ENCODING_BASE64;
$type = 'text/calendar; method=REQUEST';
$disposition = 'attachment';

$mail->addAttachment($path, $name, $encoding, $type, $disposition);
```
The addition of **method=REQUEST** to the attachment Content-Type tells Microsoft Outlook that the attached event is awaiting a response so it then adds the RSVP buttons to the interface.

For more detail on this have a look at https://stackoverflow.com/questions/66102584/when-i-add-method-request-to-icalendar-gmail-stops-recognizing-as-event

**Comment by djarran** [comment]
> The solution is actually a lot simpler than that.
> 
> Create the ical file using something like `https://kigkonsult.se/iCalcreator/` as recommended in the documentation. Then attach the file as follows:
> 
> ```
> $path= 'C:\PHPTemp\invitation.ics';
> $name = basename($path);
> $encoding = PHPMailer::ENCODING_BASE64;
> $type = 'text/calendar; method=REQUEST';
> $disposition = 'attachment';
> 
> $mail->addAttachment($path, $name, $encoding, $type, $disposition);
> ```
> 
> The addition of **method=REQUEST** to the attachment Content-Type tells Microsoft Outlook that the attached event is awaiting a response so it then adds the RSVP buttons to the interface.
> 
> For more detail on this have a look at https://stackoverflow.com/questions/66102584/when-i-add-method-request-to-icalendar-gmail-stops-recognizing-as-event

Thanks for sharing this @daveherman71. This might be what I needed. Annoyingly though, shouldn't Outlook be using the `METHOD=request` in the VCALENDAR object, and not looking at the Content-Type? Thunderbird and Gmail process this just fine

**Comment by omocinteractive** [comment]
... another problem - in PHPMailer there is no way to suppress "Content-Disposition" in invite mails with addStringAttachment (if you leave the fifth parameter empty with '', the sending will not work):

PHPMailer:
Content-Type: text/calendar; charset="utf-8"; method=REQUEST
Content-Transfer-Encoding: base64
Content-Disposition: attachment;

Outlook:
Content-Type: text/calendar; charset="utf-8"; method=REQUEST
Content-Transfer-Encoding: base64

The event is always attached as a file without usefull filename ... with filename - there is no RSVP button.

**Comment by omocinteractive** [comment]
@daveherman71: This is exactly what i did - but with empty disposition, no invitation is sent. I thing, it's a bug (not a feature ...).

**Comment by omocinteractive** [comment]
I've taken a look at the PHPMailer source code. An empty dispatch isn't processed or isn't intended. I'll submit a feature request.

**Comment by daveherman71** [comment]
Out of interest, have you tried:  `Content-Disposition: inline`

as per https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Disposition

**Comment by omocinteractive** [comment]
@daveherman71 : Yes, but no invitation is shown (Thunderbird) - here the code:
Content-Type: text/calendar; charset=utf-8; method=REQUEST
Content-Transfer-Encoding: base64
Content-ID: <0>
Content-Disposition: inline

But the correct code would be:

Content-Type: text/calendar; charset=utf-8; method=REQUEST
Content-Transfer-Encoding: base64
