### ISSUE TITLE
To Address is not showing in Header

### ISSUE THREAD

**Issue by akvarshney19** [PHPMailer/PHPMailer#397]
I am a novice in php, I am using php mailer class to send mail through SMTP. It is working absolutely fine but only To: Undisclosed recipient message is in header.
if i add any email in cc then that email is showing but not in To email:

**Comment by Synchro** [comment]
You need to call `addAddress` for each `To` recipient. Sounds like you're calling `addBCC`. When making a bug report, include **short** example code that shows the problem happening.

**Comment by akvarshney19** [comment]
I am using addAddress  function here i pass akvarshney19@yahoo.com in addAddress and iec.ankit@gmail.com in addCC.
then i am not getting To: in Header. Here output of Header is 
Delivered-To: iec.ankit@gmail.com
Received: by 10.64.235.148 with SMTP id um20csp1623187iec;
        Tue, 7 Apr 2015 06:54:09 -0700 (PDT)
X-Received: by 10.68.190.228 with SMTP id gt4mr37103372pbc.6.1428414848409;
        Tue, 07 Apr 2015 06:54:08 -0700 (PDT)
Return-Path: <neerajn@ecomexpress.in>
Received: from GOH-HUB02.hosting.local (abs1.exchangemails.com. [202.65.150.104])
        by mx.google.com with ESMTPS id fy4si11483917pbb.100.2015.04.07.06.54.07
        for <iec.ankit@gmail.com>
        (version=TLSv1 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
        Tue, 07 Apr 2015 06:54:08 -0700 (PDT)
Received-SPF: neutral (google.com: 202.65.150.104 is neither permitted nor denied by domain of neerajn@ecomexpress.in) client-ip=202.65.150.104;
Authentication-Results: mx.google.com;
       spf=neutral (google.com: 202.65.150.104 is neither permitted nor denied by domain of neerajn@ecomexpress.in) smtp.mail=neerajn@ecomexpress.in
Received: from localhost (10.1.0.156) by smtp.exchangemails.com (10.1.0.104)
 with Microsoft SMTP Server id 14.3.224.2; Tue, 7 Apr 2015 19:25:18 +0530
Date: Tue, 7 Apr 2015 19:23:59 +0530
CC: <iec.ankit@gmail.com>

**Comment by Synchro** [comment]
Post your code.

**Comment by akvarshney19** [comment]
require 'class.phpmailer.php';
require 'class.smtp.php';
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->Mailer = 'smtp';
$mail->SMTPAuth = true;
$mail->SMTPDebug = 4;
$mail->Host = 'smtp.exchangemails.com'; // "ssl://smtp.gmail.com" didn't worked
$mail->Port = 25;
//$mail->SMTPSecure = 'ssl';
// or try these settings (worked on XAMPP and WAMP):
// $mail->Port = 587;
//$mail->SMTPSecure = 'tls';
 
 
$mail->Username = "neerajn@ecomexpress.in";
$mail->Password = "#4553";
 
$mail->IsHTML(true); // if you are going to send HTML formatted emails
$mail->SingleTo = true; // if you want to send a same email to multiple users. multiple emails will be sent one-by-one.
 
$mail->From = "neerajn@ecomexpress.in";
$mail->FromName = "Ankit Varshney";
 
$mail->addAddress("akvarshney19@yahoo.com","User 1");
//$mail->addAddress("ankit.varshney@ecomexpress.in","User 2");
//$mail->addAddress("neerajn@ecomexpress.in","User 2");

 $mail->addCC("iec.ankit@gmail.com");
 //$mail->addBCC("akvarshney19@yahoo.com");

 
$mail->Subject = "Testing PHPMailer with localhost";
$mail->Body = "Hi,<br /><br />This system is working perfectly @phase1.";
 
if(!$mail->Send())
    echo "Message was not sent <br />PHPMailer Error: " . $mail->ErrorInfo;
else
    echo "Message has been sent";

**Comment by Synchro** [comment]
You've based that on an obsolete example (start with the supplied Gmail one), so you're probably using an old version of PHPMailer too.

**Comment by Irshadkhan786** [comment]
I am getting the same issue. here is my code.

   $mail = new PHPMailer();

   $mail->IsSMTP();                 

   $mail->Host   = "###.com";
   $mail->SMTPAuth  = true;
   $mail->Username  = "####";
   $mail->Password  = "####";

   $mail->Port   = 465; 

   $mail->SMTPSecure  = 'tls'; 

   $mail->Port   = 587; 
   $mail->From   = "noreply@####.com";
   $mail->FromName  = "Franchisee Mail";
   $mail->AddAddress('myemailid','irshad');
   $mail->addStringAttachment(file_get_contents($img1), $img1name);
   $mail->addStringAttachment(file_get_contents($img2), $img2name);
   $mail->IsHTML(true); 
$mail->Subject = "Franchisee Mail";                  
$mail->Body = $message;
if(!$mail->Send())
{
   echo "Mail could not be sent. <p>";
   echo "Mailer Error: " . $mail->ErrorInfo;
}
else
{
   echo "Mail sent successfully.";
}

mail is coming but to is coming blank in header section.  I have one more problem that. I mail is coming in spam folder.

**Comment by Synchro** [comment]
OK, so check the return value from that, and also enable debug output with `$mail->SMTPDebug = 2;` and inspect the SMTP traffic to see why it's not appearing.

**Comment by Synchro** [comment]
You also have `$mail->Port = 465;` **and** `$mail->Port = 587;`; the latter will be used (and is correct since you're using `SMTPSecure = 'tls'`), but suggests you're not looking at this too hard.

As far as going into the spam folder is concerned, you have no direct control over that, but you should implement SPF and ideally DKIM & DMARC too, and ensure you have a good sending reputation for your IP, and that your content is not considered spam (received headers may tell you more about why your message is in the spam folder) - though all of these are outside the scope of PHPMailer alone.

**Comment by craigkendall** [comment]
Did you solve this @Irshadkhan786 ? I just implemented a system using PHPMailer and am experiencing what I believe to be similar.

I'm getting a list of users from my database, then iterating over a foreach loop to populate the addAddress, sending that email, then clearing all recipients before iterating to the next database result. I'm posting my code below.

I'm not using the $mail->SingleTo = true; setting because I read somewhere else that it was not reliable.

The email header says I'm using PHPMailer 6.1.2

**Comment by duzun** [comment]
I think this issue is still there.

When there is `$mail->SingleTo = true;` & `$mail->isSMTP()`, then `To:` header is not added, even with single `to` address.
I switch it to `$mail->SingleTo = false;` and get the `To:` header back.

I've followed the PHPMailer code logic and I can see what is the exact issue:

When `$mail->SingleTo = true;`, the `createHeader()` method excludes the 'To:' header and collects all the `to`s in `$this->SingleToArray` property.
Next, if `$this->Mailer = 'sendmail'`, the [`sendmailSend()`](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1657) method prepends the `To:` header for each recipient.

But if `$this->Mailer = 'smtp'`, then `$mail->SingleTo` is ignored in `$this->smtpSend()`, except that `$header` does not include the 'To:' any more.

To me, this looks like a bug. I'm not sure how SMTP + SingleTo should work, but the 'To:' header missing is a real issue.

**Comment by Synchro** [comment]
Thanks for investigating, and that does sound like a bug, however, [`SingleTo` is documented as not working in SMTP](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L441), and it was also [documented as deprecated in the 6.0 release notes](https://github.com/PHPMailer/PHPMailer/blob/master/changelog.md#version-60-august-28th-2017) from 3 years ago, and it will be removed altogether in the next major release.
It should really have a `@deprecated` tag on it...

Instead of `SingleTo`, send each message separately. There's no real performance hit, and it moves the responsibility for handling >1 message into your app, where it belongs.

**Comment by duzun** [comment]
@Synchro that makes a lot of sense :)
I haven't read the documentation lately and faced the same issue with v5.

Actually, I always send emails one-by-one in the application code and set `SingleTo = true` just in case, as a safeguard.

Thanks for the clarification!
